version: '3.5'
services:
  pgadmin:
    image: dpage/pgadmin4:9.3.0
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: email@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    networks:
      network_service:
        ipv4_address: 10.10.3.30
      network_db:
        ipv4_address: 10.10.2.10

networks:
  network_service:
    external: true
  network_db:
    external: true