version: '3.5'
services:
  ubuntu:
    image: ubuntu:local
    container_name: ubuntu-maintainer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        docker_app: true
        app_essentials: true
  
  ubuntu-nd:
    image: ubuntu:not-docker
    container_name: ubuntu-maintainer-nd
    build:
      context: .
      dockerfile: Dockerfile
      args:
        docker_app: false
        app_essentials: true