version: '3.5'
services:
  youtrack:
    image: jetbrains/youtrack:2025.1.67057
    container_name: youtrack
    ports:
      - "3031:8080"
    volumes:
      - data:/opt/youtrack/data
      - conf:/opt/youtrack/conf
      - logs:/opt/youtrack/logs
      - backups:/opt/youtrack/backups
    environment:
      - JAVA_OPTS=-Ddisable.configuration.wizard.on.upgrade=true
    restart: unless-stopped
    networks:
      network_service:
        ipv4_address: 10.10.3.50
    dns:
      - 10.10.3.2

    deploy:
      resources:
        limits:
          #cpus: '2'
          memory: 3072M
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  network_service:
    external: true

volumes:
  data:
    external: false
  conf:
    external: false
  logs:
    external: false
  backups:
    external: false