services:
  fluent-bit:
    image: fluent/fluent-bit:4.1
    container_name: fluent-bit
    restart: unless-stopped
    networks:
      network_service:
        ipv4_address: 10.10.3.102
    logging:
      driver: json-file
    ports:
      - 2020:2020    # Puerto HTTP (health / metrics)
      - 24224:24224  # Puerto TCP input
      - 24224:24224/udp
    volumes:
      - /var/log:/var/log:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/machine-id:/etc/machine-id:ro
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    environment:
      - FLB_HTTP_SERVER=On
      - FLB_HTTP_LISTEN=0.0.0.0
      - FLB_HTTP_PORT=2020

networks:
  network_service:
    external: true