version: '3.5'
services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        pocket_ver: v0.27.1
    image: pocketbase:local
    container_name: pocketbase_local
    restart: unless-stopped
    ports:
      - 8090:8090
    networks:
      network_service:
        ipv4_address: 10.10.3.12
    dns:
      - 10.10.3.2

networks:
  network_service:
    external: true