version: '3.5'
services:
  sqlite:
    image: alpine:3.20
    command: tail -f /dev/null # Keeps container alive to trigger volume creation
    restart: unless-stopped
    volumes:
      - data:/data

volumes:
  data:
    external: false