# This Compose file defines two Ubuntu-based services sharing core configuration
# for user environments and network settings, using YAML anchors to enforce DRY.
version: '3.5'

# Shared settings for all Ubuntu services
x-ubuntu-base: &ubuntu-base
  image: ubuntu:local
  restart: no
  dns:
    - 8.8.8.8

# system
x-vol-shared: &vol-shared user_shared:/home/shared
x-vol-tmp: &vol-tmp user_tmp:/tmp
x-vol-log: &vol-log user_log:/var/log
x-vol-cache: &vol-cache user_cache:/var/cache
x-vol-opt: &vol-opt user_opt:/opt

# app
x-vol-conda: &vol-conda conda_app:/opt/conda

x-gpu: &gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]


# Machine-specific settings
services:
  ubuntu-luist:
    <<: *ubuntu-base
    #<<: *gpu
    container_name: "ubuntu-luist"
    privileged: true
    environment:
      USERNAME: "luist"
      PSWD: "9031"
      #NVIDIA_VISIBLE_DEVICES: "all"
    volumes:
      - *vol-shared
      - *vol-tmp
      - *vol-log
      - *vol-cache
      - *vol-opt
      - *vol-conda
      - user_data_luist:/home/luist
      - user_cache:/home/luist/.cache
    
    networks:
      network_shared:
      network_user:
      lan_net:
          ipv4_address: 192.168.1.3
      

  ubuntu-carlj:
    <<: *ubuntu-base
    #<<: *gpu
    container_name: "ubuntu-carlj"
    privileged: true
    environment:
      USERNAME: "carlj"
      PSWD: "9031"
      #NVIDIA_VISIBLE_DEVICES: "all"
    volumes:
      - *vol-shared
      - *vol-tmp
      - *vol-log
      - *vol-cache
      - *vol-opt
      - user_data_carlj:/home/carlj
      - user_cache:/home/carlj/.cache
    
    networks:
      network_shared:
      network_user:

volumes:

  # User-specific volumes
  user_data_luist:
    external: false
  

  user_data_carlj:
    external: false
  
  conda_app:
    external: true

  # Shared volumes
  user_tmp:
    external: false
  user_log:
    external: false
  user_cache:
    external: false
  user_shared:
    external: false
  user_opt:
    external: false

networks:
  network_user:
    external: true
  network_shared:
    external: true
  lan_net:
    external: true