# This Compose file defines two Ubuntu-based services sharing core configuration
# for user environments and network settings, using YAML anchors to enforce DRY.
version: '3.5'

# Shared settings for all Ubuntu services
x-ubuntu-base: &ubuntu-base
  image: ubuntu:local
  restart: unless-stopped
  dns:
    - 10.10.4.3

x-ubuntu-nd: &ubuntu-nd
  image: ubuntu:not-docker
  restart: unless-stopped
  dns:
    - 10.10.4.3

# System
x-vol-shared: &vol-shared user_shared:/home/shared
x-vol-tmp: &vol-tmp user_tmp:/tmp
x-vol-log: &vol-log user_log:/var/log
x-vol-cache: &vol-cache user_cache:/var/cache
x-vol-opt: &vol-opt user_opt:/opt

# Conda volumes
x-conda-25: &vol-conda-25 conda_app_25:/opt/conda
x-conda-4: &vol-conda-4 conda_app_4:/opt/conda

# Machine-specific settings
services:
  ubuntu-luist:
    <<: *ubuntu-base
    container_name: "ubuntu-luist"
    privileged: true
    ports:
      - "2220:22"
    environment:
      USERNAME: "luist"
      PSWD: "0000"
    volumes:
      - *vol-shared
      - *vol-tmp
      - *vol-log
      - *vol-cache
      - *vol-opt
      - *vol-conda-25
      - user_data_luist:/home/luist
      - user_cache:/home/luist/.cache

    networks:
      network_user:
        ipv4_address: 10.10.4.10
      network_shared:

  ubuntu-carlj:
    <<: *ubuntu-nd # out docker
    container_name: "ubuntu-carlj"
    privileged: true
    environment:
      USERNAME: "carlj"
      PSWD: "0000"
    ports:
      - "2221:22"
    volumes:
      - *vol-shared
      - *vol-tmp
      - *vol-log
      - *vol-cache
      - *vol-opt
      - *vol-conda-4
      - user_data_carlj:/home/carlj
      - user_cache:/home/carlj/.cache
    
    networks:
      network_user:
        ipv4_address: 10.10.4.11
      network_shared:

volumes:
  user_data_luist:
    external: false
  user_data_carlj:
    external: false
  
  # Conda volumes
  conda_app_4:
    external: true
  conda_app_25:
    external: true

  # Shared volumes
  user_tmp:
    external: false
  user_log:
    external: false
  user_cache:
    external: false
  user_shared:
    external: false
  user_opt:
    external: false

networks:
  network_user:
    external: true
  network_shared:
    external: true