version: '3.5'

services:
  ubuntu-user:
    image: ubuntu:local
    container_name: ubuntu-user
    environment:
      - USERNAME=luist
      - USER_UID=1000
      - USER_GID=1000
      - USER_PASSWORD=3956
    volumes:
      - conda_app:/opt/conda
    restart: "no"
    networks:
      lan_net:
        ipv4_address: 192.168.1.100

volumes:
  conda_app:
    external: true

networks:
  lan_net:
    external: true
    # docker network create --driver=macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 -o parent=enp1s0 lan_net