# This Compose file defines two Ubuntu-based services sharing core configuration
# for user environments and network settings, using YAML anchors to enforce DRY.

# Shared settings for all Ubuntu services
x-ubuntu-base: &ubuntu-base
  image: ubuntu:local
  restart: unless-stopped
  privileged: true
  dns:
    - 10.10.4.200

# System
x-vol-shared: &vol-shared user_shared:/home/shared
x-vol-tmp: &vol-tmp user_tmp:/tmp
x-vol-log: &vol-log user_log:/var/log
x-vol-cache: &vol-cache user_cache:/var/cache
x-vol-opt: &vol-opt user_opt:/opt

# Machine-specific settings
services:
  ubuntu:
    <<: *ubuntu-base
    container_name: "ubuntu-${USER}"
    ports:
      - "2220:22"
    environment:
      USERNAME: ${USER}
      PSWD: ${PASSWORD}
    volumes:
      - *vol-shared
      - *vol-tmp
      - *vol-log
      - *vol-cache
      - *vol-opt
      - user_data:/home/${USER}
      - user_cache:/home/${USER}/.cache
      - dind:/var/lib/docker
      - etc:/etc

    networks:
      network_user:
        ipv4_address: 10.10.4.10
      network_shared:
      network_service:

volumes:
  user_data:
    external: false
  dind:
    external: false
  etc:
    external: false

  # Shared volumes
  user_tmp:
    external: false
  user_log:
    external: false
  user_cache:
    external: false
  user_shared:
    external: false
  user_opt:
    external: false

networks:
  network_user:
    external: true
  network_shared:
    external: true
  network_service:
    external: true