version: "3.5"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=America/Bogota
      - SUBDOMAINS=,
      - TOKEN=
      - LOG_FILE=false
    volumes:
      - ./duckdns/appdata/config:/config #optional
    restart: unless-stopped