version: '3.5'
services:
  hbbs:
    container_name: rustdesk-hbbs
    image: rustdesk/rustdesk-server:1.1.9-amd64 # version important
    command: hbbs
    volumes:
      - data:/root
    network_mode: "host"
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: rustdesk-hbbr
    image: rustdesk/rustdesk-server:1.1.9-amd64
    command: hbbr
    volumes:
      - data:/root
    network_mode: "host"
    restart: unless-stopped

volumes:
  data:
    external: false