services:
  loki:
    image: grafana/loki:3.4
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      network_service:
        ipv4_address: 10.10.3.100 # port: 3100

  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3200:3000"
    networks:
      network_service:
        ipv4_address: 10.10.3.101
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - data:/var/lib/grafana
    depends_on:
      - loki

networks:
  network_service:
    external: true

volumes:
  data:
    external: false