version: '2.1'

services:
  jupyter:
    image: ubuntu:local
    container_name: notebook
    ports:
      - 8888:8888
      - 4422:22
    environment:
      - USERNAME=jupyter
      - PSWD=jupyter
    restart: unless-stopped
    volumes:
      - workspace_research:/home/research
      - conda_opt:/opt/conda
      - julia_opt:/opt/julia
      - data:/home/jupyter
    command: >
      bash -c "source /opt/conda/bin/activate && \
               conda activate jupyter && \
               jupyter lab --config=/home/jupyter/.jupyter/jupyter_lab_config.py --allow-root --ip=0.0.0.0 --port=8888 --no-browser"

    dns:
      - 8.8.8.8

volumes:
  data:
    external: false
  
  conda_opt:
    external: true

  julia_opt:
    external: true

  workspace_research:
    external: true