version: '3.5'
services:
  penpot_redis:
    image: redis:7.2
    container_name: penpot_redis
    #REDIS_PASSWORD:
    volumes:
      - penpot:/data
    networks:
      network_db:
        ipv4_address: 10.10.2.41 # :6379
      network_service:
        ipv4_address: 10.10.3.141
    restart: unless-stopped
  
  langfuse_redis:
    image: redis:7.2
    container_name: langfuse_redis
    restart: unless-stopped
    # CHANGEME: row below to secure redis password
    command: >
      --requirepass ${REDIS_AUTH:-myredissecret}
    volumes:
      - langfuse:/data
    networks:
      network_db:
        ipv4_address: 10.10.2.42 # :6379
      network_service:
        ipv4_address: 10.10.3.142
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 10
  
  shared_redis:
    image: redis:7.2
    container_name: shared_redis
    restart: unless-stopped
    volumes:
      - shared:/data
    networks:
      network_db:
        ipv4_address: 10.10.2.43 # :6379
      network_service:
        ipv4_address: 10.10.3.143
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 10


volumes:
  penpot:
    external: false
  langfuse:
    external: false
  shared:
    external: false

networks:
  network_db:
    external: true
  network_service:
    external: true