version: '3.5'
services:
  penpot_redis:
    image: redis:7.2
    container_name: penpot_redis
    #REDIS_PASSWORD:
    volumes:
      - penpot:/data
    networks:
      network_db:
        ipv4_address: 10.10.2.41 # :6379
      network_service:
        ipv4_address: 10.10.3.150
    restart: unless-stopped

volumes:
  penpot:
    external: false

networks:
  network_db:
    external: true
  network_service:
    external: true