version: '3.5'
services:
  redis:
    image: redis:7.2
    container_name: redis_cache
    restart: unless-stopped
    volumes:
      - data:/data
    environment:
      REDIS_PASSWORD: '0000'
    networks:
      network_db:
        ipv4_address: 10.10.2.40
    ports:
      - "6379:6379"
  
  penpot_redis:
    image: redis:7.2
    container_name: penpot_redis
    volumes:
      - penpot:/data
    networks:
      network_db:
        ipv4_address: 10.10.2.41
      network_service:
        ipv4_address: 10.10.3.150
    restart: unless-stopped

volumes:
  data:
    external: false
  penpot:
    external: false

networks:
  network_db:
    external: true
  network_service:
    external: true