services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3
    container_name: woodpecker-server
    restart: always
    ports:
      - "8001:8000"  # UI en http://localhost:8001
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_ADMIN=admin
      - WOODPECKER_AGENT_SECRET=supersecret123
      - WOODPECKER_HOST=http://0.0.0.0:8001
      - WOODPECKER_GRPC_ADDR=0.0.0.0:9000
      - WOODPECKER_SERVER_ADDR=0.0.0.0:8000
      - WOODPECKER_DATABASE_DRIVER=sqlite3
      - WOODPECKER_DATABASE_DATASOURCE=/var/lib/woodpecker/woodpecker.sqlite3
    volumes:
      - woodpecker-data:/var/lib/woodpecker

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3
    container_name: woodpecker-agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=supersecret123
      - WOODPECKER_MAX_WORKFLOWS=2

volumes:
  woodpecker-data:
