services:
  pihole:
    container_name: dns_pihole
    image: pihole/pihole:2025.07.1
    environment:
      TZ: 'America/Bogota'
      WEBPASSWORD: '0000'
    volumes:
      - data:/etc/pihole/
      - dnsmasq:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    ports:
      - 8081:80
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 443:443
    networks:
      network_security:
        ipv4_address: 10.10.5.200 # :53/tcp/udp :67/udp :443/tcp :80/tcp
      network_user:
        ipv4_address: 10.10.4.200
      network_service:
        ipv4_address: 10.10.3.200

networks:
  network_security:
    external: true
  network_service:
    external: true
  network_user:
    external: true

volumes:
  data:
    external: false
  dnsmasq:  
    external: false
