version: '3.5'
services:
  pihole:
    container_name: dns_pihole
    image: pihole/pihole:v5.7
    environment:
      TZ: 'America/Bogota'
      WEBPASSWORD: '0000'
    volumes:
      - data:/etc/pihole/
      - dnsmasq:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      network_security:
        ipv4_address: 10.10.5.2 # :53/tcp/udp :67/udp :443/tcp :80/tcp
      network_service:
        ipv4_address: 10.10.3.2

networks:
  network_security:
    external: true
  network_service:
    external: true

volumes:
  data:
    external: false
  dnsmasq:  
    external: false