version: '3.5'
services:
  pihole:
    container_name: dns_pihole
    image: pihole/pihole:v5.7
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "443:443/tcp"
      - "8000:80/tcp"
    environment:
      TZ: 'America/Bogota'
      WEBPASSWORD: '0000'
    volumes:
      - data:/etc/pihole/
      - dnsmasq:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      network_security:
        ipv4_address: 10.10.5.2

networks:
  network_security:
    external: true

volumes:
  data:
    external: false
  dnsmasq:  
    external: false