version: '3.5'
services:
  miniconda3_25:
    image: minconda:local
    container_name: conda-maintainer-25
    build:
      context: .
      dockerfile: Dockerfile
      args:
        conda_ver: 25.1.1-2
    volumes:
      - opt:/conda

volumes:
  opt:
    external: false
