version: '3.5'
services:
  cuda-11:
    image: cuda:local-11
    container_name: cuda-maintainer-11
    build:
      context: .
      dockerfile: Dockerfile
      args:
        cuda_ver: 11.8.0
    volumes:
        - driver_11:/usr/local/cuda
  
  cuda-12:
    image: cuda:local-12
    container_name: cuda-maintainer-12
    build:
      context: .
      dockerfile: Dockerfile
      args:
        cuda_ver: 12.1.0
    volumes:
        - driver_12:/usr/local/cuda

volumes:
  driver_11:
    external: false
  
  driver_12:
    external: false