version: "3.5"

services:
  noip-duc:
    container_name: noip-duc
    image: ghcr.io/noipcom/noip-duc:3.2.0
    restart: unless-stopped
    networks:
      network_security:
    environment:
      - NOIP_USERNAME=${NOIP_USERNAME}
      - NOIP_PASSWORD=${NOIP_PASSWORD}
      - NOIP_HOSTNAMES=${NOIP_HOSTNAMES}
    dns:
      - 10.10.5.3

networks:
  network_security:
    external: true